# 张量的数学运算

张量数学运算主要有：标量运算，向量运算，矩阵运算。另外我们会介绍张量运算的广播机制。



# 标量运算

张量的数学运算符可以分为标量运算符、向量运算符、以及矩阵运算符。加减乘除乘方，以及三角函数，指数，对数等常见函数，逻辑比较运算符等都是标量运算符。

标量运算符的特点是对张量实施逐元素运算。有些标量运算符对常用的数学运算符进行了重载。并且支持类似 numpy 的广播特性。许多标量运算符都在 tf.math 模块下。


In [1]:
import tensorflow as tf 
import numpy as np 

In [19]:
a = tf.constant([[1.0,2],[-3,4.0]])
b = tf.constant([[5.0,6],[7.0,8.0]])

tf.print(a + b)  #运算符重载
tf.print(a - b)
tf.print(a * b)
tf.print(a / b)
tf.print(a ** 2)
tf.print(a ** 0.5)
tf.print(a % 3)
tf.print(a >= 2)

[[6 8]
 [4 12]]
[[-4 -4]
 [-10 -4]]
[[5 12]
 [-21 32]]
[[0.2 0.333333343]
 [-0.428571433 0.5]]
[[1 4]
 [9 16]]
[[1 1.41421354]
 [-nan 2]]
[[1 2]
 [-0 1]]
[[0 1]
 [0 1]]


In [15]:
tf.print((a>=2)&(a<=3))

tf.print((a>=2)|(a<=3))

tf.print(a==5)

tf.print(tf.sqrt(a))

[0 0]
[1 1]
[0 0]
[1 2.82842708]


In [14]:
a = tf.constant([1.0,8.0])
b = tf.constant([5.0,6.0])
c = tf.constant([6.0,7.0])
tf.add_n([a,b,c])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>

In [ ]:
tf.print(tf.maximum(a,b))

tf.print(tf.minimum(a,b))

x = tf.constant([2.6,-2.7])

tf.print(tf.math.round(x)) #保留整数部分，四舍五入
tf.print(tf.math.floor(x)) #保留整数部分，向下归整
tf.print(tf.math.ceil(x))  #保留整数部分，向上归整

# 幅值裁剪
x = tf.constant([0.9,-0.8,100.0,-20.0,0.7])
y = tf.clip_by_value(x,clip_value_min=-1,clip_value_max=1)
z = tf.clip_by_norm(x,clip_norm = 3)
tf.print(y)
tf.print(z)

# 向量运算

向量运算符只在一个特定轴上运算，将一个向量映射到一个标量或者另外一个向量。 许多向量运算符都以 reduce 开头。



In [22]:
# 向量 reduce
a = tf.range(1,10)
tf.print(tf.reduce_sum(a))
tf.print(tf.reduce_mean(a))
tf.print(tf.reduce_max(a))
tf.print(tf.reduce_min(a))
tf.print(tf.reduce_prod(a))

# 张量指定维度进行reduce
b = tf.reshape(a,(3,3))
tf.print(tf.reduce_sum(b, axis=1, keepdims=True))
tf.print(tf.reduce_sum(b, axis=0, keepdims=True))

# bool类型的reduce
p = tf.constant([True,False,False])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

# 利用tf.foldr实现tf.reduce_sum
s = tf.foldr(lambda a,b:a+b,tf.range(10)) 
tf.print(s)

# cum扫描累积
a = tf.range(1,10)
tf.print(tf.math.cumsum(a))
tf.print(tf.math.cumprod(a))

# arg最大最小值索引
a = tf.range(1,10)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))

# tf.math.top_k可以用于对张量排序
a = tf.constant([1,3,7,5,4,8])

values,indices = tf.math.top_k(a,3,sorted=True)
tf.print(values)
tf.print(indices)

#利用tf.math.top_k可以在TensorFlow中实现KNN算法

45
5
9
1
362880
[[6]
 [15]
 [24]]
[[12 15 18]]
0
1
45
[1 3 6 ... 28 36 45]
[1 2 6 ... 5040 40320 362880]
8
0
[8 7 5]
[5 2 3]


# 矩阵运算


矩阵必须是二维的。类似tf.constant([1,2,3])这样的不是矩阵。矩阵运算包括：矩阵乘法，矩阵转置，矩阵逆，矩阵求迹，矩阵范数，矩阵行列式，矩阵求特征值，矩阵分解等运算。除了一些常用的运算外，大部分和矩阵有关的运算都在tf.linalg子包中。



In [25]:
# 矩阵乘法
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])
tf.print(a@b)  #等价于tf.matmul(a,b)

# 矩阵转置
a = tf.constant([[1,2],[3,4]])
tf.transpose(a)

# 矩阵逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0,2],[3,4]],dtype = tf.float32)
tf.linalg.inv(a)

# 矩阵求 trace
a = tf.constant([[1.0,2],[3,4]],dtype = tf.float32)
tf.linalg.trace(a)

# 矩阵求范数
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.norm(a)

# 矩阵行列式
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.det(a)

# 矩阵特征值
a = tf.constant([[1.0,2],[-5,4]])
tf.linalg.eigvals(a)

# 矩阵QR分解, 将一个方阵分解为一个正交矩阵q和上三角矩阵r
# QR分解实际上是对矩阵a实施Schmidt正交化得到q

a = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

# 矩阵svd分解
# svd分解可以将任意一个矩阵分解为一个正交矩阵u,一个对角阵s和一个正交矩阵v.t()的乘积
# svd常用于矩阵压缩和降维

a  = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]], dtype = tf.float32)
s,u,v = tf.linalg.svd(a)
tf.print(u,"\n")
tf.print(s,"\n")
tf.print(v,"\n")
tf.print(u@tf.linalg.diag(s)@tf.transpose(v))

# 利用svd分解可以在TensorFlow中实现主成分分析降维

[[2 4]
 [6 8]]
[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227764]]
[[-3.1622777 -4.4271884]
 [0 -0.632455409]]
[[1.00000012 1.99999988]
 [3 3.99999976]]
[[0.229847804 -0.883461118]
 [0.524744928 -0.240782872]
 [0.819642 0.401896209]] 

[9.52552 0.514300048] 

[[0.619629562 0.784894466]
 [0.784894466 -0.619629562]] 

[[1.00000155 2.00000095]
 [3.00000167 4.00000191]
 [5.00000191 6.00000191]]


# 广播机制

TensorFlow的广播规则和numpy是一样的:

- 1、如果张量的维度不同，将维度较小的张量进行扩展，直到两个张量的维度都一样。
- 2、如果两个张量在某个维度上的长度是相同的，或者其中一个张量在该维度上的长度为1，那么我们就说这两个张量在该维度上是相容的。
- 3、如果两个张量在所有维度上都是相容的，它们就能使用广播。
- 4、广播之后，每个维度的长度将取两个张量在该维度长度的较大值。
- 5、在任何一个维度上，如果一个张量的长度为1，另一个张量长度大于1，那么在该维度上，就好像是对第一个张量进行了复制。

tf.broadcast_to 以显式的方式按照广播机制扩展张量的维度。

In [26]:
a = tf.constant([1,2,3])
b = tf.constant([[0,0,0],[1,1,1],[2,2,2]])
b + a  # 等价于 b + tf.broadcast_to(a,b.shape)

tf.broadcast_to(a,b.shape)

# 计算广播后计算结果的形状，静态形状，TensorShape类型参数
tf.broadcast_static_shape(a.shape,b.shape)

# 计算广播后计算结果的形状，动态形状，Tensor类型参数
c = tf.constant([1,2,3])
d = tf.constant([[1],[2],[3]])
tf.broadcast_dynamic_shape(tf.shape(c),tf.shape(d))

# 广播效果
c+d # 等价于 tf.broadcast_to(c,[3,3]) + tf.broadcast_to(d,[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int32)>